name: GitHub CI

on: [push, pull_request]

jobs:
  ubuntu-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libevent-dev libseccomp-dev git libsasl2-dev
        
    - name: prepare building
      run: |
        gcc --version
        ./autogen.sh
        ./configure --enable-seccomp --enable-tls --enable-sasl --enable-sasl-pwdb
        
    - name: Coderrect Scan
      uses: coderrect-inc/coderrect-github-action@main
      with:
        buildCommand: "make -j"
        options: "-analyzeBinaries=memcached,memcached-debug"
        exit0: true
    
    - name: build
      run: |
        make clean
        make -j
